services:
  pitsinkr:
    build: .
    container_name: pitsinkr
    ports:
      - "53:53/udp"
      - "4004:4004"
      - "9056:9056"
    volumes:
      - pitsinkr_data:/app/data
    restart: unless-stopped
