services:
  pitsinkr:
    build: .
    container_name: pitsinkr
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "4004:4004"
      - "9056:9056"
    restart: unless-stopped
